### ISSUE TITLE
新增：aardio 由 Jacen 主导的中国编程语言

### ISSUE THREAD

**Issue by isPoto** [chai2010/china-programming-languages#28]
aardio 是一门设计优秀的编程语言。IDE 大小仅 6.5 MB，却能开发Win桌面软件、开发网站。且语法简洁优雅。比起其他实验性的语言项目，aardio 更具备实用性，属于能实际应用，用来干活的编程语言。意义巨大。

https://www.aardio.com/

**Comment by nobodxbodon** [comment]
Jacen He：[百度百科](https://baike.baidu.com/item/aardio/55878444)

**Comment by chai2010** [comment]
这是开源项目吗？如果是可以提交pr

**Comment by nobodxbodon** [comment]
@chai2010 它的标准库开源了：https://mp.weixin.qq.com/s/VBV5px3IPrJR40kpEk5M-w
从它的历史和用户反馈来看，已经是相当成熟实用的语言工具项目：https://www.toutiao.com/article/7128984127860359684
个人认为应有一席之地。

**Comment by chai2010** [comment]
我双手赞成其不开源的决定，不过闭源软件的玩法是花钱找渠道推广。这里主要是收录开源的语言，因为我们也只是因为兴趣用爱发电

**Comment by isPoto** [comment]
> 我双手赞成其不开源的决定，不过闭源软件的玩法是花钱找渠道推广。这里主要是收录开源的语言，因为我们也只是因为兴趣用爱发电

aardio 是免费商用，内核不开源是因为保护开发者利益。因为开源的编程语言逆向都很容易。
aardio 并没有花钱找渠道推广，你可以看到 aardio 主要是作者一个人在默默耕耘，甚至你之前没有听说过。

aardio 是完全免费可商用且不要求任何条件，除内核外的库均开源。

aardio 作者是用爱发电，你给作者捐赠他不要的。

aardio 比目前列举的编程语言，在实用性、设计架构和实际应用上均明显超越。可谓是中国唯一拿得出手的编程语言。你可以看得到业内人士对 aardio 的称赞。

本项目的名称是「中国编程语言」，结果你附加条件是开源的语言，这实属不妥。中国编程语言和开源是两码事，如果因为开不开源决定是否作为「中国编程语言」的唯一决定条件，请把项目名改掉，不要用这种虚大空、挂着中国的名号作为项目名。因为这样做实际上是开源语言收录，与中国编程语言无关。

因为不开源，所以开除中国编程语言国籍，未免儿戏且片面。

说句难听的话，aardio 比目前本项目收录的所有语言都来得实际、有价值和有意义。它能真正用来开发商用项目，能真正应用在实际社会中。而本项目目前收录的语言，基本上是实验、Demo 和 PPT 性质，能做点东西但并不足以真正应用。而且论能力也不足以跟十多年发展的 aardio 相比。

我这里并没有对目前本项目收录的编程语言不尊敬的意思。但就事论事，如果你说 aardio 因为它不是开源（实际上只是内核不开源，其他库均开源），就不予以收录，你这项目还是不要用中国编程语言这个名号。

但凡是个业内人士，看到目前收录的有新意没实意的编程语言，却没有真正能拿得出手的 aardio，都会摇摇头。

**Comment by isPoto** [comment]
> @chai2010 它的标准库开源了：https://mp.weixin.qq.com/s/VBV5px3IPrJR40kpEk5M-w 从它的历史和用户反馈来看，已经是相当成熟实用的语言工具项目：https://www.toutiao.com/article/7128984127860359684 个人认为应有一席之地。

算了吧，项目主页详情页写死了只收录开源的。
打着「中国编程语言」结果却只收录开源的，啧啧。

既然这样，为什么不把项目名改成「中国开源编程语言」，非要打着「中国编程语言」的幌子。

没这么大的气量还挂着中国的名号，这个项目不会有人信服的。

**Comment by hax** [comment]
@nobodxbodon 它开源的标准库仓库在哪里？

**Comment by nobodxbodon** [comment]
@hax 在上面那篇《借力打力》里提到了，我还没看到在线repo，不过在官方下载包解压之后，看到lib下的大量aardio源码大概就是：
<img width="1013" alt="Screen Shot 2022-08-28 at 4 31 53 PM" src="https://user-images.githubusercontent.com/392497/187099231-96caf9bc-7d97-4247-ac65-641ba11020c6.png">

**Comment by nobodxbodon** [comment]
@hax 官方文档 [此处提到](https://bbs.aardio.com/doc/reference/libraries/import.html)：

> 标准库(Standard Libraries)
标准库由 aardio开发环境 提供。
位于aardio根目录下的lib目录下，库路径与名字空间路径完全一致。

**Comment by hax** [comment]
仅仅可以看到源码不能算开源。他至少得有基本的许可证说明，如果有不同的贡献者那最好要有比较完善的贡献记录（否则版权是不清晰的）。而我们现在意义上的开源其实还包含以开源方式协作开发，通常是基于源码仓库如github、gitlab或gitee之类的。当然这并不是必须的，传统上电子邮件发送diff、patch之类的方式也行，但这就有点像在现代社会出行硬要骑马一样……

**Comment by nobodxbodon** [comment]
@hax 刚得知解压包中有`help/用户许可协议/aardio开源代码许可证.txt`

**Comment by chai2010** [comment]
开源协议没有关系。关键是语言核心和编译器需要开放代码，个人用户能免费使用。只公开标准库代码没有多少意义
